# coding: utf-8

"""
    dlpapi

    Easily and directly scan and detect sensitive data (PII) in input text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_dlp_api_client
from cloudmersive_dlp_api_client.api.tasks_batch_job_api import TasksBatchJobApi  # noqa: E501
from cloudmersive_dlp_api_client.rest import ApiException


class TestTasksBatchJobApi(unittest.TestCase):
    """TasksBatchJobApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_dlp_api_client.api.tasks_batch_job_api.TasksBatchJobApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_detect_audio_advanced_batch_job(self):
        """Test case for detect_audio_advanced_batch_job

        Detect User Data in Audio File (Advanced) as a Batch Job  # noqa: E501
        """
        pass

    def test_detect_audio_batch_job(self):
        """Test case for detect_audio_batch_job

        Detect User Data in Audio File as a Batch Job  # noqa: E501
        """
        pass

    def test_get_async_job_status(self):
        """Test case for get_async_job_status

        Get the status and result of a DLP Batch Job  # noqa: E501
        """
        pass

    def test_redact_audio_advanced_batch_job(self):
        """Test case for redact_audio_advanced_batch_job

        Redact User Data in Audio File (Advanced) as a Batch Job  # noqa: E501
        """
        pass

    def test_redact_audio_batch_job(self):
        """Test case for redact_audio_batch_job

        Redact User Data in Audio File as a Batch Job  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
