# coding: utf-8

"""
    dlpapi

    Easily and directly scan and detect sensitive data (PII) in input text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_phishing_api_client
from cloudmersive_phishing_api_client.api.detect_api import DetectApi  # noqa: E501
from cloudmersive_phishing_api_client.rest import ApiException


class TestDetectApi(unittest.TestCase):
    """DetectApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_phishing_api_client.api.detect_api.DetectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_detect_document(self):
        """Test case for detect_document

        Detect User Data in Document Image  # noqa: E501
        """
        pass

    def test_detect_document_advanced(self):
        """Test case for detect_document_advanced

        Detect User Data in Document Image (Advanced)  # noqa: E501
        """
        pass

    def test_detect_text(self):
        """Test case for detect_text

        Detect User Data in Input Text  # noqa: E501
        """
        pass

    def test_detect_text_advanced(self):
        """Test case for detect_text_advanced

        Detect User Data in Input Text (Advanced)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
