# coding: utf-8

"""
    dlpapi

    Easily and directly scan and detect sensitive data (PII) in input text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_dlp_api_client
from cloudmersive_dlp_api_client.models.audio_timestamp import AudioTimestamp  # noqa: E501
from cloudmersive_dlp_api_client.rest import ApiException


class TestAudioTimestamp(unittest.TestCase):
    """AudioTimestamp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAudioTimestamp(self):
        """Test AudioTimestamp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_dlp_api_client.models.audio_timestamp.AudioTimestamp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
