# coding: utf-8

"""
    dlpapi

    Easily and directly scan and detect sensitive data (PII) in input text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_dlp_api_client
from cloudmersive_dlp_api_client.models.custom_pii_field import CustomPiiField  # noqa: E501
from cloudmersive_dlp_api_client.rest import ApiException


class TestCustomPiiField(unittest.TestCase):
    """CustomPiiField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomPiiField(self):
        """Test CustomPiiField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_dlp_api_client.models.custom_pii_field.CustomPiiField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
