# coding: utf-8

"""
    dlpapi

    Easily and directly scan and detect sensitive data (PII) in input text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_phishing_api_client
from cloudmersive_phishing_api_client.models.dlp_detection_request import DlpDetectionRequest  # noqa: E501
from cloudmersive_phishing_api_client.rest import ApiException


class TestDlpDetectionRequest(unittest.TestCase):
    """DlpDetectionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDlpDetectionRequest(self):
        """Test DlpDetectionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_phishing_api_client.models.dlp_detection_request.DlpDetectionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
