# coding: utf-8

"""
    dlpapi

    Easily and directly scan and detect sensitive data (PII) in input text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_phishing_api_client
from cloudmersive_phishing_api_client.api.redact_api import RedactApi  # noqa: E501
from cloudmersive_phishing_api_client.rest import ApiException


class TestRedactApi(unittest.TestCase):
    """RedactApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_phishing_api_client.api.redact_api.RedactApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_redact_document(self):
        """Test case for redact_document

        Redact User Data in Document  # noqa: E501
        """
        pass

    def test_redact_document_advanced(self):
        """Test case for redact_document_advanced

        Redact User Data in Document (Advanced)  # noqa: E501
        """
        pass

    def test_redact_text(self):
        """Test case for redact_text

        Redact User Data in Input Text  # noqa: E501
        """
        pass

    def test_redact_text_advanced(self):
        """Test case for redact_text_advanced

        Redact User Data in Input Text (Advanced)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
