# coding: utf-8

"""
    dlpapi

    Easily and directly scan and detect sensitive data (PII) in input text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DlpAdvancedDetectionResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'clean_result': 'bool',
        'contains_email_address': 'bool',
        'contains_phone_number': 'bool',
        'contains_street_address': 'bool',
        'contains_person_name': 'bool',
        'contains_birth_date': 'bool',
        'contains_passport_number': 'bool',
        'contains_drivers_license': 'bool',
        'contains_social_security_number': 'bool',
        'contains_taxpayer_id': 'bool',
        'contains_credit_card_number': 'bool',
        'contains_credit_card_expiration_date': 'bool',
        'contains_credit_card_verification_code': 'bool',
        'contains_bank_account_number': 'bool',
        'contains_iban': 'bool',
        'contains_health_insurance_number': 'bool',
        'contains_bearer_token': 'bool',
        'contains_http_cookie': 'bool',
        'contains_private_keys': 'bool',
        'contains_credentials': 'bool',
        'contains_deep_web_urls': 'bool',
        'contains_source_code': 'bool',
        'contains_ip_address': 'bool',
        'contains_mac_address': 'bool',
        'contains_health_insurance_member_id': 'bool',
        'contains_health_injury_or_disease': 'bool',
        'contains_health_type_of_treatment': 'bool',
        'contains_health_date_and_time_of_treatment': 'bool',
        'contains_health_plan_beneficiary_number': 'bool',
        'contains_health_payments_made_for_treatment': 'bool',
        'contains_faces': 'bool',
        'contains_vehicle_id': 'bool',
        'contains_device_id': 'bool',
        'contains_names_of_relatives': 'bool',
        'contains_health_universal_record_locator': 'bool',
        'contains_biometrics': 'bool',
        'analysis_rationale': 'str'
    }

    attribute_map = {
        'clean_result': 'CleanResult',
        'contains_email_address': 'ContainsEmailAddress',
        'contains_phone_number': 'ContainsPhoneNumber',
        'contains_street_address': 'ContainsStreetAddress',
        'contains_person_name': 'ContainsPersonName',
        'contains_birth_date': 'ContainsBirthDate',
        'contains_passport_number': 'ContainsPassportNumber',
        'contains_drivers_license': 'ContainsDriversLicense',
        'contains_social_security_number': 'ContainsSocialSecurityNumber',
        'contains_taxpayer_id': 'ContainsTaxpayerID',
        'contains_credit_card_number': 'ContainsCreditCardNumber',
        'contains_credit_card_expiration_date': 'ContainsCreditCardExpirationDate',
        'contains_credit_card_verification_code': 'ContainsCreditCardVerificationCode',
        'contains_bank_account_number': 'ContainsBankAccountNumber',
        'contains_iban': 'ContainsIBAN',
        'contains_health_insurance_number': 'ContainsHealthInsuranceNumber',
        'contains_bearer_token': 'ContainsBearerToken',
        'contains_http_cookie': 'ContainsHttpCookie',
        'contains_private_keys': 'ContainsPrivateKeys',
        'contains_credentials': 'ContainsCredentials',
        'contains_deep_web_urls': 'ContainsDeepWebUrls',
        'contains_source_code': 'ContainsSourceCode',
        'contains_ip_address': 'ContainsIpAddress',
        'contains_mac_address': 'ContainsMacAddress',
        'contains_health_insurance_member_id': 'ContainsHealthInsuranceMemberID',
        'contains_health_injury_or_disease': 'ContainsHealthInjuryOrDisease',
        'contains_health_type_of_treatment': 'ContainsHealthTypeOfTreatment',
        'contains_health_date_and_time_of_treatment': 'ContainsHealthDateAndTimeOfTreatment',
        'contains_health_plan_beneficiary_number': 'ContainsHealthPlanBeneficiaryNumber',
        'contains_health_payments_made_for_treatment': 'ContainsHealthPaymentsMadeForTreatment',
        'contains_faces': 'ContainsFaces',
        'contains_vehicle_id': 'ContainsVehicleID',
        'contains_device_id': 'ContainsDeviceID',
        'contains_names_of_relatives': 'ContainsNamesOfRelatives',
        'contains_health_universal_record_locator': 'ContainsHealthUniversalRecordLocator',
        'contains_biometrics': 'ContainsBiometrics',
        'analysis_rationale': 'AnalysisRationale'
    }

    def __init__(self, clean_result=None, contains_email_address=None, contains_phone_number=None, contains_street_address=None, contains_person_name=None, contains_birth_date=None, contains_passport_number=None, contains_drivers_license=None, contains_social_security_number=None, contains_taxpayer_id=None, contains_credit_card_number=None, contains_credit_card_expiration_date=None, contains_credit_card_verification_code=None, contains_bank_account_number=None, contains_iban=None, contains_health_insurance_number=None, contains_bearer_token=None, contains_http_cookie=None, contains_private_keys=None, contains_credentials=None, contains_deep_web_urls=None, contains_source_code=None, contains_ip_address=None, contains_mac_address=None, contains_health_insurance_member_id=None, contains_health_injury_or_disease=None, contains_health_type_of_treatment=None, contains_health_date_and_time_of_treatment=None, contains_health_plan_beneficiary_number=None, contains_health_payments_made_for_treatment=None, contains_faces=None, contains_vehicle_id=None, contains_device_id=None, contains_names_of_relatives=None, contains_health_universal_record_locator=None, contains_biometrics=None, analysis_rationale=None):  # noqa: E501
        """DlpAdvancedDetectionResponse - a model defined in Swagger"""  # noqa: E501

        self._clean_result = None
        self._contains_email_address = None
        self._contains_phone_number = None
        self._contains_street_address = None
        self._contains_person_name = None
        self._contains_birth_date = None
        self._contains_passport_number = None
        self._contains_drivers_license = None
        self._contains_social_security_number = None
        self._contains_taxpayer_id = None
        self._contains_credit_card_number = None
        self._contains_credit_card_expiration_date = None
        self._contains_credit_card_verification_code = None
        self._contains_bank_account_number = None
        self._contains_iban = None
        self._contains_health_insurance_number = None
        self._contains_bearer_token = None
        self._contains_http_cookie = None
        self._contains_private_keys = None
        self._contains_credentials = None
        self._contains_deep_web_urls = None
        self._contains_source_code = None
        self._contains_ip_address = None
        self._contains_mac_address = None
        self._contains_health_insurance_member_id = None
        self._contains_health_injury_or_disease = None
        self._contains_health_type_of_treatment = None
        self._contains_health_date_and_time_of_treatment = None
        self._contains_health_plan_beneficiary_number = None
        self._contains_health_payments_made_for_treatment = None
        self._contains_faces = None
        self._contains_vehicle_id = None
        self._contains_device_id = None
        self._contains_names_of_relatives = None
        self._contains_health_universal_record_locator = None
        self._contains_biometrics = None
        self._analysis_rationale = None
        self.discriminator = None

        if clean_result is not None:
            self.clean_result = clean_result
        if contains_email_address is not None:
            self.contains_email_address = contains_email_address
        if contains_phone_number is not None:
            self.contains_phone_number = contains_phone_number
        if contains_street_address is not None:
            self.contains_street_address = contains_street_address
        if contains_person_name is not None:
            self.contains_person_name = contains_person_name
        if contains_birth_date is not None:
            self.contains_birth_date = contains_birth_date
        if contains_passport_number is not None:
            self.contains_passport_number = contains_passport_number
        if contains_drivers_license is not None:
            self.contains_drivers_license = contains_drivers_license
        if contains_social_security_number is not None:
            self.contains_social_security_number = contains_social_security_number
        if contains_taxpayer_id is not None:
            self.contains_taxpayer_id = contains_taxpayer_id
        if contains_credit_card_number is not None:
            self.contains_credit_card_number = contains_credit_card_number
        if contains_credit_card_expiration_date is not None:
            self.contains_credit_card_expiration_date = contains_credit_card_expiration_date
        if contains_credit_card_verification_code is not None:
            self.contains_credit_card_verification_code = contains_credit_card_verification_code
        if contains_bank_account_number is not None:
            self.contains_bank_account_number = contains_bank_account_number
        if contains_iban is not None:
            self.contains_iban = contains_iban
        if contains_health_insurance_number is not None:
            self.contains_health_insurance_number = contains_health_insurance_number
        if contains_bearer_token is not None:
            self.contains_bearer_token = contains_bearer_token
        if contains_http_cookie is not None:
            self.contains_http_cookie = contains_http_cookie
        if contains_private_keys is not None:
            self.contains_private_keys = contains_private_keys
        if contains_credentials is not None:
            self.contains_credentials = contains_credentials
        if contains_deep_web_urls is not None:
            self.contains_deep_web_urls = contains_deep_web_urls
        if contains_source_code is not None:
            self.contains_source_code = contains_source_code
        if contains_ip_address is not None:
            self.contains_ip_address = contains_ip_address
        if contains_mac_address is not None:
            self.contains_mac_address = contains_mac_address
        if contains_health_insurance_member_id is not None:
            self.contains_health_insurance_member_id = contains_health_insurance_member_id
        if contains_health_injury_or_disease is not None:
            self.contains_health_injury_or_disease = contains_health_injury_or_disease
        if contains_health_type_of_treatment is not None:
            self.contains_health_type_of_treatment = contains_health_type_of_treatment
        if contains_health_date_and_time_of_treatment is not None:
            self.contains_health_date_and_time_of_treatment = contains_health_date_and_time_of_treatment
        if contains_health_plan_beneficiary_number is not None:
            self.contains_health_plan_beneficiary_number = contains_health_plan_beneficiary_number
        if contains_health_payments_made_for_treatment is not None:
            self.contains_health_payments_made_for_treatment = contains_health_payments_made_for_treatment
        if contains_faces is not None:
            self.contains_faces = contains_faces
        if contains_vehicle_id is not None:
            self.contains_vehicle_id = contains_vehicle_id
        if contains_device_id is not None:
            self.contains_device_id = contains_device_id
        if contains_names_of_relatives is not None:
            self.contains_names_of_relatives = contains_names_of_relatives
        if contains_health_universal_record_locator is not None:
            self.contains_health_universal_record_locator = contains_health_universal_record_locator
        if contains_biometrics is not None:
            self.contains_biometrics = contains_biometrics
        if analysis_rationale is not None:
            self.analysis_rationale = analysis_rationale

    @property
    def clean_result(self):
        """Gets the clean_result of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if no disallowed PII or sensitive data types were detected in the input text; false if any disallowed type was found.  # noqa: E501

        :return: The clean_result of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._clean_result

    @clean_result.setter
    def clean_result(self, clean_result):
        """Sets the clean_result of this DlpAdvancedDetectionResponse.

        True if no disallowed PII or sensitive data types were detected in the input text; false if any disallowed type was found.  # noqa: E501

        :param clean_result: The clean_result of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._clean_result = clean_result

    @property
    def contains_email_address(self):
        """Gets the contains_email_address of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains email addresses.  # noqa: E501

        :return: The contains_email_address of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_email_address

    @contains_email_address.setter
    def contains_email_address(self, contains_email_address):
        """Sets the contains_email_address of this DlpAdvancedDetectionResponse.

        True if the input text contains email addresses.  # noqa: E501

        :param contains_email_address: The contains_email_address of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_email_address = contains_email_address

    @property
    def contains_phone_number(self):
        """Gets the contains_phone_number of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains phone numbers.  # noqa: E501

        :return: The contains_phone_number of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_phone_number

    @contains_phone_number.setter
    def contains_phone_number(self, contains_phone_number):
        """Sets the contains_phone_number of this DlpAdvancedDetectionResponse.

        True if the input text contains phone numbers.  # noqa: E501

        :param contains_phone_number: The contains_phone_number of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_phone_number = contains_phone_number

    @property
    def contains_street_address(self):
        """Gets the contains_street_address of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains street addresses.  # noqa: E501

        :return: The contains_street_address of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_street_address

    @contains_street_address.setter
    def contains_street_address(self, contains_street_address):
        """Sets the contains_street_address of this DlpAdvancedDetectionResponse.

        True if the input text contains street addresses.  # noqa: E501

        :param contains_street_address: The contains_street_address of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_street_address = contains_street_address

    @property
    def contains_person_name(self):
        """Gets the contains_person_name of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains person names.  # noqa: E501

        :return: The contains_person_name of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_person_name

    @contains_person_name.setter
    def contains_person_name(self, contains_person_name):
        """Sets the contains_person_name of this DlpAdvancedDetectionResponse.

        True if the input text contains person names.  # noqa: E501

        :param contains_person_name: The contains_person_name of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_person_name = contains_person_name

    @property
    def contains_birth_date(self):
        """Gets the contains_birth_date of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains birth dates.  # noqa: E501

        :return: The contains_birth_date of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_birth_date

    @contains_birth_date.setter
    def contains_birth_date(self, contains_birth_date):
        """Sets the contains_birth_date of this DlpAdvancedDetectionResponse.

        True if the input text contains birth dates.  # noqa: E501

        :param contains_birth_date: The contains_birth_date of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_birth_date = contains_birth_date

    @property
    def contains_passport_number(self):
        """Gets the contains_passport_number of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains passport numbers.  # noqa: E501

        :return: The contains_passport_number of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_passport_number

    @contains_passport_number.setter
    def contains_passport_number(self, contains_passport_number):
        """Sets the contains_passport_number of this DlpAdvancedDetectionResponse.

        True if the input text contains passport numbers.  # noqa: E501

        :param contains_passport_number: The contains_passport_number of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_passport_number = contains_passport_number

    @property
    def contains_drivers_license(self):
        """Gets the contains_drivers_license of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains drivers license numbers.  # noqa: E501

        :return: The contains_drivers_license of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_drivers_license

    @contains_drivers_license.setter
    def contains_drivers_license(self, contains_drivers_license):
        """Sets the contains_drivers_license of this DlpAdvancedDetectionResponse.

        True if the input text contains drivers license numbers.  # noqa: E501

        :param contains_drivers_license: The contains_drivers_license of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_drivers_license = contains_drivers_license

    @property
    def contains_social_security_number(self):
        """Gets the contains_social_security_number of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains social security numbers.  # noqa: E501

        :return: The contains_social_security_number of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_social_security_number

    @contains_social_security_number.setter
    def contains_social_security_number(self, contains_social_security_number):
        """Sets the contains_social_security_number of this DlpAdvancedDetectionResponse.

        True if the input text contains social security numbers.  # noqa: E501

        :param contains_social_security_number: The contains_social_security_number of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_social_security_number = contains_social_security_number

    @property
    def contains_taxpayer_id(self):
        """Gets the contains_taxpayer_id of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains taxpayer IDs.  # noqa: E501

        :return: The contains_taxpayer_id of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_taxpayer_id

    @contains_taxpayer_id.setter
    def contains_taxpayer_id(self, contains_taxpayer_id):
        """Sets the contains_taxpayer_id of this DlpAdvancedDetectionResponse.

        True if the input text contains taxpayer IDs.  # noqa: E501

        :param contains_taxpayer_id: The contains_taxpayer_id of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_taxpayer_id = contains_taxpayer_id

    @property
    def contains_credit_card_number(self):
        """Gets the contains_credit_card_number of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains credit card numbers.  # noqa: E501

        :return: The contains_credit_card_number of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_credit_card_number

    @contains_credit_card_number.setter
    def contains_credit_card_number(self, contains_credit_card_number):
        """Sets the contains_credit_card_number of this DlpAdvancedDetectionResponse.

        True if the input text contains credit card numbers.  # noqa: E501

        :param contains_credit_card_number: The contains_credit_card_number of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_credit_card_number = contains_credit_card_number

    @property
    def contains_credit_card_expiration_date(self):
        """Gets the contains_credit_card_expiration_date of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains credit card expiration dates.  # noqa: E501

        :return: The contains_credit_card_expiration_date of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_credit_card_expiration_date

    @contains_credit_card_expiration_date.setter
    def contains_credit_card_expiration_date(self, contains_credit_card_expiration_date):
        """Sets the contains_credit_card_expiration_date of this DlpAdvancedDetectionResponse.

        True if the input text contains credit card expiration dates.  # noqa: E501

        :param contains_credit_card_expiration_date: The contains_credit_card_expiration_date of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_credit_card_expiration_date = contains_credit_card_expiration_date

    @property
    def contains_credit_card_verification_code(self):
        """Gets the contains_credit_card_verification_code of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains credit card verification codes.  # noqa: E501

        :return: The contains_credit_card_verification_code of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_credit_card_verification_code

    @contains_credit_card_verification_code.setter
    def contains_credit_card_verification_code(self, contains_credit_card_verification_code):
        """Sets the contains_credit_card_verification_code of this DlpAdvancedDetectionResponse.

        True if the input text contains credit card verification codes.  # noqa: E501

        :param contains_credit_card_verification_code: The contains_credit_card_verification_code of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_credit_card_verification_code = contains_credit_card_verification_code

    @property
    def contains_bank_account_number(self):
        """Gets the contains_bank_account_number of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains bank account numbers.  # noqa: E501

        :return: The contains_bank_account_number of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_bank_account_number

    @contains_bank_account_number.setter
    def contains_bank_account_number(self, contains_bank_account_number):
        """Sets the contains_bank_account_number of this DlpAdvancedDetectionResponse.

        True if the input text contains bank account numbers.  # noqa: E501

        :param contains_bank_account_number: The contains_bank_account_number of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_bank_account_number = contains_bank_account_number

    @property
    def contains_iban(self):
        """Gets the contains_iban of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains IBANs.  # noqa: E501

        :return: The contains_iban of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_iban

    @contains_iban.setter
    def contains_iban(self, contains_iban):
        """Sets the contains_iban of this DlpAdvancedDetectionResponse.

        True if the input text contains IBANs.  # noqa: E501

        :param contains_iban: The contains_iban of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_iban = contains_iban

    @property
    def contains_health_insurance_number(self):
        """Gets the contains_health_insurance_number of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains health insurance numbers.  # noqa: E501

        :return: The contains_health_insurance_number of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_health_insurance_number

    @contains_health_insurance_number.setter
    def contains_health_insurance_number(self, contains_health_insurance_number):
        """Sets the contains_health_insurance_number of this DlpAdvancedDetectionResponse.

        True if the input text contains health insurance numbers.  # noqa: E501

        :param contains_health_insurance_number: The contains_health_insurance_number of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_health_insurance_number = contains_health_insurance_number

    @property
    def contains_bearer_token(self):
        """Gets the contains_bearer_token of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains bearer tokens.  # noqa: E501

        :return: The contains_bearer_token of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_bearer_token

    @contains_bearer_token.setter
    def contains_bearer_token(self, contains_bearer_token):
        """Sets the contains_bearer_token of this DlpAdvancedDetectionResponse.

        True if the input text contains bearer tokens.  # noqa: E501

        :param contains_bearer_token: The contains_bearer_token of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_bearer_token = contains_bearer_token

    @property
    def contains_http_cookie(self):
        """Gets the contains_http_cookie of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains HTTP cookies.  # noqa: E501

        :return: The contains_http_cookie of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_http_cookie

    @contains_http_cookie.setter
    def contains_http_cookie(self, contains_http_cookie):
        """Sets the contains_http_cookie of this DlpAdvancedDetectionResponse.

        True if the input text contains HTTP cookies.  # noqa: E501

        :param contains_http_cookie: The contains_http_cookie of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_http_cookie = contains_http_cookie

    @property
    def contains_private_keys(self):
        """Gets the contains_private_keys of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains private keys.  # noqa: E501

        :return: The contains_private_keys of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_private_keys

    @contains_private_keys.setter
    def contains_private_keys(self, contains_private_keys):
        """Sets the contains_private_keys of this DlpAdvancedDetectionResponse.

        True if the input text contains private keys.  # noqa: E501

        :param contains_private_keys: The contains_private_keys of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_private_keys = contains_private_keys

    @property
    def contains_credentials(self):
        """Gets the contains_credentials of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains credentials (usernames/passwords).  # noqa: E501

        :return: The contains_credentials of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_credentials

    @contains_credentials.setter
    def contains_credentials(self, contains_credentials):
        """Sets the contains_credentials of this DlpAdvancedDetectionResponse.

        True if the input text contains credentials (usernames/passwords).  # noqa: E501

        :param contains_credentials: The contains_credentials of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_credentials = contains_credentials

    @property
    def contains_deep_web_urls(self):
        """Gets the contains_deep_web_urls of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains deep web URLs (.onion).  # noqa: E501

        :return: The contains_deep_web_urls of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_deep_web_urls

    @contains_deep_web_urls.setter
    def contains_deep_web_urls(self, contains_deep_web_urls):
        """Sets the contains_deep_web_urls of this DlpAdvancedDetectionResponse.

        True if the input text contains deep web URLs (.onion).  # noqa: E501

        :param contains_deep_web_urls: The contains_deep_web_urls of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_deep_web_urls = contains_deep_web_urls

    @property
    def contains_source_code(self):
        """Gets the contains_source_code of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains source code.  # noqa: E501

        :return: The contains_source_code of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_source_code

    @contains_source_code.setter
    def contains_source_code(self, contains_source_code):
        """Sets the contains_source_code of this DlpAdvancedDetectionResponse.

        True if the input text contains source code.  # noqa: E501

        :param contains_source_code: The contains_source_code of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_source_code = contains_source_code

    @property
    def contains_ip_address(self):
        """Gets the contains_ip_address of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains IP addresses.  # noqa: E501

        :return: The contains_ip_address of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_ip_address

    @contains_ip_address.setter
    def contains_ip_address(self, contains_ip_address):
        """Sets the contains_ip_address of this DlpAdvancedDetectionResponse.

        True if the input text contains IP addresses.  # noqa: E501

        :param contains_ip_address: The contains_ip_address of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_ip_address = contains_ip_address

    @property
    def contains_mac_address(self):
        """Gets the contains_mac_address of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains MAC addresses.  # noqa: E501

        :return: The contains_mac_address of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_mac_address

    @contains_mac_address.setter
    def contains_mac_address(self, contains_mac_address):
        """Sets the contains_mac_address of this DlpAdvancedDetectionResponse.

        True if the input text contains MAC addresses.  # noqa: E501

        :param contains_mac_address: The contains_mac_address of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_mac_address = contains_mac_address

    @property
    def contains_health_insurance_member_id(self):
        """Gets the contains_health_insurance_member_id of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains health insurance member IDs.  # noqa: E501

        :return: The contains_health_insurance_member_id of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_health_insurance_member_id

    @contains_health_insurance_member_id.setter
    def contains_health_insurance_member_id(self, contains_health_insurance_member_id):
        """Sets the contains_health_insurance_member_id of this DlpAdvancedDetectionResponse.

        True if the input text contains health insurance member IDs.  # noqa: E501

        :param contains_health_insurance_member_id: The contains_health_insurance_member_id of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_health_insurance_member_id = contains_health_insurance_member_id

    @property
    def contains_health_injury_or_disease(self):
        """Gets the contains_health_injury_or_disease of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains references to injuries or diseases.  # noqa: E501

        :return: The contains_health_injury_or_disease of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_health_injury_or_disease

    @contains_health_injury_or_disease.setter
    def contains_health_injury_or_disease(self, contains_health_injury_or_disease):
        """Sets the contains_health_injury_or_disease of this DlpAdvancedDetectionResponse.

        True if the input text contains references to injuries or diseases.  # noqa: E501

        :param contains_health_injury_or_disease: The contains_health_injury_or_disease of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_health_injury_or_disease = contains_health_injury_or_disease

    @property
    def contains_health_type_of_treatment(self):
        """Gets the contains_health_type_of_treatment of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains references to types of medical treatment.  # noqa: E501

        :return: The contains_health_type_of_treatment of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_health_type_of_treatment

    @contains_health_type_of_treatment.setter
    def contains_health_type_of_treatment(self, contains_health_type_of_treatment):
        """Sets the contains_health_type_of_treatment of this DlpAdvancedDetectionResponse.

        True if the input text contains references to types of medical treatment.  # noqa: E501

        :param contains_health_type_of_treatment: The contains_health_type_of_treatment of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_health_type_of_treatment = contains_health_type_of_treatment

    @property
    def contains_health_date_and_time_of_treatment(self):
        """Gets the contains_health_date_and_time_of_treatment of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains dates and times of medical treatment.  # noqa: E501

        :return: The contains_health_date_and_time_of_treatment of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_health_date_and_time_of_treatment

    @contains_health_date_and_time_of_treatment.setter
    def contains_health_date_and_time_of_treatment(self, contains_health_date_and_time_of_treatment):
        """Sets the contains_health_date_and_time_of_treatment of this DlpAdvancedDetectionResponse.

        True if the input text contains dates and times of medical treatment.  # noqa: E501

        :param contains_health_date_and_time_of_treatment: The contains_health_date_and_time_of_treatment of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_health_date_and_time_of_treatment = contains_health_date_and_time_of_treatment

    @property
    def contains_health_plan_beneficiary_number(self):
        """Gets the contains_health_plan_beneficiary_number of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains health plan beneficiary numbers.  # noqa: E501

        :return: The contains_health_plan_beneficiary_number of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_health_plan_beneficiary_number

    @contains_health_plan_beneficiary_number.setter
    def contains_health_plan_beneficiary_number(self, contains_health_plan_beneficiary_number):
        """Sets the contains_health_plan_beneficiary_number of this DlpAdvancedDetectionResponse.

        True if the input text contains health plan beneficiary numbers.  # noqa: E501

        :param contains_health_plan_beneficiary_number: The contains_health_plan_beneficiary_number of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_health_plan_beneficiary_number = contains_health_plan_beneficiary_number

    @property
    def contains_health_payments_made_for_treatment(self):
        """Gets the contains_health_payments_made_for_treatment of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input text contains payments made for medical treatment.  # noqa: E501

        :return: The contains_health_payments_made_for_treatment of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_health_payments_made_for_treatment

    @contains_health_payments_made_for_treatment.setter
    def contains_health_payments_made_for_treatment(self, contains_health_payments_made_for_treatment):
        """Sets the contains_health_payments_made_for_treatment of this DlpAdvancedDetectionResponse.

        True if the input text contains payments made for medical treatment.  # noqa: E501

        :param contains_health_payments_made_for_treatment: The contains_health_payments_made_for_treatment of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_health_payments_made_for_treatment = contains_health_payments_made_for_treatment

    @property
    def contains_faces(self):
        """Gets the contains_faces of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the document contains identifiable human faces.  # noqa: E501

        :return: The contains_faces of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_faces

    @contains_faces.setter
    def contains_faces(self, contains_faces):
        """Sets the contains_faces of this DlpAdvancedDetectionResponse.

        True if the document contains identifiable human faces.  # noqa: E501

        :param contains_faces: The contains_faces of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_faces = contains_faces

    @property
    def contains_vehicle_id(self):
        """Gets the contains_vehicle_id of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input contains vehicle identifiers (e.g. license plates, VINs).  # noqa: E501

        :return: The contains_vehicle_id of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_vehicle_id

    @contains_vehicle_id.setter
    def contains_vehicle_id(self, contains_vehicle_id):
        """Sets the contains_vehicle_id of this DlpAdvancedDetectionResponse.

        True if the input contains vehicle identifiers (e.g. license plates, VINs).  # noqa: E501

        :param contains_vehicle_id: The contains_vehicle_id of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_vehicle_id = contains_vehicle_id

    @property
    def contains_device_id(self):
        """Gets the contains_device_id of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input contains device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs).  # noqa: E501

        :return: The contains_device_id of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_device_id

    @contains_device_id.setter
    def contains_device_id(self, contains_device_id):
        """Sets the contains_device_id of this DlpAdvancedDetectionResponse.

        True if the input contains device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs).  # noqa: E501

        :param contains_device_id: The contains_device_id of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_device_id = contains_device_id

    @property
    def contains_names_of_relatives(self):
        """Gets the contains_names_of_relatives of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input contains names of relatives.  # noqa: E501

        :return: The contains_names_of_relatives of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_names_of_relatives

    @contains_names_of_relatives.setter
    def contains_names_of_relatives(self, contains_names_of_relatives):
        """Sets the contains_names_of_relatives of this DlpAdvancedDetectionResponse.

        True if the input contains names of relatives.  # noqa: E501

        :param contains_names_of_relatives: The contains_names_of_relatives of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_names_of_relatives = contains_names_of_relatives

    @property
    def contains_health_universal_record_locator(self):
        """Gets the contains_health_universal_record_locator of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input contains health universal record locators (URLs).  # noqa: E501

        :return: The contains_health_universal_record_locator of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_health_universal_record_locator

    @contains_health_universal_record_locator.setter
    def contains_health_universal_record_locator(self, contains_health_universal_record_locator):
        """Sets the contains_health_universal_record_locator of this DlpAdvancedDetectionResponse.

        True if the input contains health universal record locators (URLs).  # noqa: E501

        :param contains_health_universal_record_locator: The contains_health_universal_record_locator of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_health_universal_record_locator = contains_health_universal_record_locator

    @property
    def contains_biometrics(self):
        """Gets the contains_biometrics of this DlpAdvancedDetectionResponse.  # noqa: E501

        True if the input contains biometric data references (e.g. fingerprints, retinal scans, voiceprints).  # noqa: E501

        :return: The contains_biometrics of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._contains_biometrics

    @contains_biometrics.setter
    def contains_biometrics(self, contains_biometrics):
        """Sets the contains_biometrics of this DlpAdvancedDetectionResponse.

        True if the input contains biometric data references (e.g. fingerprints, retinal scans, voiceprints).  # noqa: E501

        :param contains_biometrics: The contains_biometrics of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: bool
        """

        self._contains_biometrics = contains_biometrics

    @property
    def analysis_rationale(self):
        """Gets the analysis_rationale of this DlpAdvancedDetectionResponse.  # noqa: E501

        Rationale for why the conclusion was formed. Only populated when ProvideAnalysisRationale is set to true in the request.  # noqa: E501

        :return: The analysis_rationale of this DlpAdvancedDetectionResponse.  # noqa: E501
        :rtype: str
        """
        return self._analysis_rationale

    @analysis_rationale.setter
    def analysis_rationale(self, analysis_rationale):
        """Sets the analysis_rationale of this DlpAdvancedDetectionResponse.

        Rationale for why the conclusion was formed. Only populated when ProvideAnalysisRationale is set to true in the request.  # noqa: E501

        :param analysis_rationale: The analysis_rationale of this DlpAdvancedDetectionResponse.  # noqa: E501
        :type: str
        """

        self._analysis_rationale = analysis_rationale

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DlpAdvancedDetectionResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DlpAdvancedDetectionResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
