# coding: utf-8

"""
    dlpapi

    Easily and directly scan and detect sensitive data (PII) in input text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DlpAdvancedAudioDetectionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'input_file': 'str',
        'language_code': 'str',
        'allow_email_address': 'bool',
        'allow_phone_number': 'bool',
        'allow_street_address': 'bool',
        'allow_city': 'bool',
        'allow_person_name': 'bool',
        'allow_birth_date': 'bool',
        'allow_passport_number': 'bool',
        'allow_drivers_license': 'bool',
        'allow_social_security_number': 'bool',
        'allow_taxpayer_id': 'bool',
        'allow_credit_card_number': 'bool',
        'allow_credit_card_expiration_date': 'bool',
        'allow_credit_card_verification_code': 'bool',
        'allow_bank_account_number': 'bool',
        'allow_iban': 'bool',
        'allow_health_insurance_number': 'bool',
        'allow_bearer_token': 'bool',
        'allow_http_cookie': 'bool',
        'allow_private_keys': 'bool',
        'allow_credentials': 'bool',
        'allow_deep_web_urls': 'bool',
        'allow_source_code': 'bool',
        'allow_ip_address': 'bool',
        'allow_mac_address': 'bool',
        'allow_health_insurance_member_id': 'bool',
        'allow_medical_record_number': 'bool',
        'allow_billing_account_number': 'bool',
        'allow_health_injury_or_disease': 'bool',
        'allow_health_type_of_treatment': 'bool',
        'allow_health_date_and_time_of_treatment': 'bool',
        'allow_health_plan_beneficiary_number': 'bool',
        'allow_health_payments_made_for_treatment': 'bool',
        'allow_vehicle_id': 'bool',
        'allow_device_id': 'bool',
        'allow_names_of_relatives': 'bool',
        'allow_health_universal_record_locator': 'bool',
        'allow_biometrics': 'bool',
        'provide_analysis_rationale': 'bool',
        'custom_policy_id': 'str'
    }

    attribute_map = {
        'input_file': 'InputFile',
        'language_code': 'LanguageCode',
        'allow_email_address': 'AllowEmailAddress',
        'allow_phone_number': 'AllowPhoneNumber',
        'allow_street_address': 'AllowStreetAddress',
        'allow_city': 'AllowCity',
        'allow_person_name': 'AllowPersonName',
        'allow_birth_date': 'AllowBirthDate',
        'allow_passport_number': 'AllowPassportNumber',
        'allow_drivers_license': 'AllowDriversLicense',
        'allow_social_security_number': 'AllowSocialSecurityNumber',
        'allow_taxpayer_id': 'AllowTaxpayerID',
        'allow_credit_card_number': 'AllowCreditCardNumber',
        'allow_credit_card_expiration_date': 'AllowCreditCardExpirationDate',
        'allow_credit_card_verification_code': 'AllowCreditCardVerificationCode',
        'allow_bank_account_number': 'AllowBankAccountNumber',
        'allow_iban': 'AllowIBAN',
        'allow_health_insurance_number': 'AllowHealthInsuranceNumber',
        'allow_bearer_token': 'AllowBearerToken',
        'allow_http_cookie': 'AllowHttpCookie',
        'allow_private_keys': 'AllowPrivateKeys',
        'allow_credentials': 'AllowCredentials',
        'allow_deep_web_urls': 'AllowDeepWebUrls',
        'allow_source_code': 'AllowSourceCode',
        'allow_ip_address': 'AllowIpAddress',
        'allow_mac_address': 'AllowMacAddress',
        'allow_health_insurance_member_id': 'AllowHealthInsuranceMemberID',
        'allow_medical_record_number': 'AllowMedicalRecordNumber',
        'allow_billing_account_number': 'AllowBillingAccountNumber',
        'allow_health_injury_or_disease': 'AllowHealthInjuryOrDisease',
        'allow_health_type_of_treatment': 'AllowHealthTypeOfTreatment',
        'allow_health_date_and_time_of_treatment': 'AllowHealthDateAndTimeOfTreatment',
        'allow_health_plan_beneficiary_number': 'AllowHealthPlanBeneficiaryNumber',
        'allow_health_payments_made_for_treatment': 'AllowHealthPaymentsMadeForTreatment',
        'allow_vehicle_id': 'AllowVehicleID',
        'allow_device_id': 'AllowDeviceID',
        'allow_names_of_relatives': 'AllowNamesOfRelatives',
        'allow_health_universal_record_locator': 'AllowHealthUniversalRecordLocator',
        'allow_biometrics': 'AllowBiometrics',
        'provide_analysis_rationale': 'ProvideAnalysisRationale',
        'custom_policy_id': 'CustomPolicyID'
    }

    def __init__(self, input_file=None, language_code=None, allow_email_address=None, allow_phone_number=None, allow_street_address=None, allow_city=None, allow_person_name=None, allow_birth_date=None, allow_passport_number=None, allow_drivers_license=None, allow_social_security_number=None, allow_taxpayer_id=None, allow_credit_card_number=None, allow_credit_card_expiration_date=None, allow_credit_card_verification_code=None, allow_bank_account_number=None, allow_iban=None, allow_health_insurance_number=None, allow_bearer_token=None, allow_http_cookie=None, allow_private_keys=None, allow_credentials=None, allow_deep_web_urls=None, allow_source_code=None, allow_ip_address=None, allow_mac_address=None, allow_health_insurance_member_id=None, allow_medical_record_number=None, allow_billing_account_number=None, allow_health_injury_or_disease=None, allow_health_type_of_treatment=None, allow_health_date_and_time_of_treatment=None, allow_health_plan_beneficiary_number=None, allow_health_payments_made_for_treatment=None, allow_vehicle_id=None, allow_device_id=None, allow_names_of_relatives=None, allow_health_universal_record_locator=None, allow_biometrics=None, provide_analysis_rationale=None, custom_policy_id=None):  # noqa: E501
        """DlpAdvancedAudioDetectionRequest - a model defined in Swagger"""  # noqa: E501

        self._input_file = None
        self._language_code = None
        self._allow_email_address = None
        self._allow_phone_number = None
        self._allow_street_address = None
        self._allow_city = None
        self._allow_person_name = None
        self._allow_birth_date = None
        self._allow_passport_number = None
        self._allow_drivers_license = None
        self._allow_social_security_number = None
        self._allow_taxpayer_id = None
        self._allow_credit_card_number = None
        self._allow_credit_card_expiration_date = None
        self._allow_credit_card_verification_code = None
        self._allow_bank_account_number = None
        self._allow_iban = None
        self._allow_health_insurance_number = None
        self._allow_bearer_token = None
        self._allow_http_cookie = None
        self._allow_private_keys = None
        self._allow_credentials = None
        self._allow_deep_web_urls = None
        self._allow_source_code = None
        self._allow_ip_address = None
        self._allow_mac_address = None
        self._allow_health_insurance_member_id = None
        self._allow_medical_record_number = None
        self._allow_billing_account_number = None
        self._allow_health_injury_or_disease = None
        self._allow_health_type_of_treatment = None
        self._allow_health_date_and_time_of_treatment = None
        self._allow_health_plan_beneficiary_number = None
        self._allow_health_payments_made_for_treatment = None
        self._allow_vehicle_id = None
        self._allow_device_id = None
        self._allow_names_of_relatives = None
        self._allow_health_universal_record_locator = None
        self._allow_biometrics = None
        self._provide_analysis_rationale = None
        self._custom_policy_id = None
        self.discriminator = None

        if input_file is not None:
            self.input_file = input_file
        if language_code is not None:
            self.language_code = language_code
        if allow_email_address is not None:
            self.allow_email_address = allow_email_address
        if allow_phone_number is not None:
            self.allow_phone_number = allow_phone_number
        if allow_street_address is not None:
            self.allow_street_address = allow_street_address
        if allow_city is not None:
            self.allow_city = allow_city
        if allow_person_name is not None:
            self.allow_person_name = allow_person_name
        if allow_birth_date is not None:
            self.allow_birth_date = allow_birth_date
        if allow_passport_number is not None:
            self.allow_passport_number = allow_passport_number
        if allow_drivers_license is not None:
            self.allow_drivers_license = allow_drivers_license
        if allow_social_security_number is not None:
            self.allow_social_security_number = allow_social_security_number
        if allow_taxpayer_id is not None:
            self.allow_taxpayer_id = allow_taxpayer_id
        if allow_credit_card_number is not None:
            self.allow_credit_card_number = allow_credit_card_number
        if allow_credit_card_expiration_date is not None:
            self.allow_credit_card_expiration_date = allow_credit_card_expiration_date
        if allow_credit_card_verification_code is not None:
            self.allow_credit_card_verification_code = allow_credit_card_verification_code
        if allow_bank_account_number is not None:
            self.allow_bank_account_number = allow_bank_account_number
        if allow_iban is not None:
            self.allow_iban = allow_iban
        if allow_health_insurance_number is not None:
            self.allow_health_insurance_number = allow_health_insurance_number
        if allow_bearer_token is not None:
            self.allow_bearer_token = allow_bearer_token
        if allow_http_cookie is not None:
            self.allow_http_cookie = allow_http_cookie
        if allow_private_keys is not None:
            self.allow_private_keys = allow_private_keys
        if allow_credentials is not None:
            self.allow_credentials = allow_credentials
        if allow_deep_web_urls is not None:
            self.allow_deep_web_urls = allow_deep_web_urls
        if allow_source_code is not None:
            self.allow_source_code = allow_source_code
        if allow_ip_address is not None:
            self.allow_ip_address = allow_ip_address
        if allow_mac_address is not None:
            self.allow_mac_address = allow_mac_address
        if allow_health_insurance_member_id is not None:
            self.allow_health_insurance_member_id = allow_health_insurance_member_id
        if allow_medical_record_number is not None:
            self.allow_medical_record_number = allow_medical_record_number
        if allow_billing_account_number is not None:
            self.allow_billing_account_number = allow_billing_account_number
        if allow_health_injury_or_disease is not None:
            self.allow_health_injury_or_disease = allow_health_injury_or_disease
        if allow_health_type_of_treatment is not None:
            self.allow_health_type_of_treatment = allow_health_type_of_treatment
        if allow_health_date_and_time_of_treatment is not None:
            self.allow_health_date_and_time_of_treatment = allow_health_date_and_time_of_treatment
        if allow_health_plan_beneficiary_number is not None:
            self.allow_health_plan_beneficiary_number = allow_health_plan_beneficiary_number
        if allow_health_payments_made_for_treatment is not None:
            self.allow_health_payments_made_for_treatment = allow_health_payments_made_for_treatment
        if allow_vehicle_id is not None:
            self.allow_vehicle_id = allow_vehicle_id
        if allow_device_id is not None:
            self.allow_device_id = allow_device_id
        if allow_names_of_relatives is not None:
            self.allow_names_of_relatives = allow_names_of_relatives
        if allow_health_universal_record_locator is not None:
            self.allow_health_universal_record_locator = allow_health_universal_record_locator
        if allow_biometrics is not None:
            self.allow_biometrics = allow_biometrics
        if provide_analysis_rationale is not None:
            self.provide_analysis_rationale = provide_analysis_rationale
        if custom_policy_id is not None:
            self.custom_policy_id = custom_policy_id

    @property
    def input_file(self):
        """Gets the input_file of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Audio file bytes (WAV, MP3, M4A, FLAC, OGG, or WMA) to transcribe and scan for PII and sensitive data.  # noqa: E501

        :return: The input_file of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: str
        """
        return self._input_file

    @input_file.setter
    def input_file(self, input_file):
        """Sets the input_file of this DlpAdvancedAudioDetectionRequest.

        Audio file bytes (WAV, MP3, M4A, FLAC, OGG, or WMA) to transcribe and scan for PII and sensitive data.  # noqa: E501

        :param input_file: The input_file of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: str
        """
        if input_file is not None and not re.search(r'^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$', input_file):  # noqa: E501
            raise ValueError(r"Invalid value for `input_file`, must be a follow pattern or equal to `/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/`")  # noqa: E501

        self._input_file = input_file

    @property
    def language_code(self):
        """Gets the language_code of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Language code for speech recognition. Default is \"ENG\" (English).  # noqa: E501

        :return: The language_code of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: str
        """
        return self._language_code

    @language_code.setter
    def language_code(self, language_code):
        """Sets the language_code of this DlpAdvancedAudioDetectionRequest.

        Language code for speech recognition. Default is \"ENG\" (English).  # noqa: E501

        :param language_code: The language_code of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: str
        """

        self._language_code = language_code

    @property
    def allow_email_address(self):
        """Gets the allow_email_address of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow email addresses in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_email_address of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_email_address

    @allow_email_address.setter
    def allow_email_address(self, allow_email_address):
        """Sets the allow_email_address of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow email addresses in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_email_address: The allow_email_address of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_email_address = allow_email_address

    @property
    def allow_phone_number(self):
        """Gets the allow_phone_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow phone numbers in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_phone_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_phone_number

    @allow_phone_number.setter
    def allow_phone_number(self, allow_phone_number):
        """Sets the allow_phone_number of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow phone numbers in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_phone_number: The allow_phone_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_phone_number = allow_phone_number

    @property
    def allow_street_address(self):
        """Gets the allow_street_address of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow street addresses in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_street_address of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_street_address

    @allow_street_address.setter
    def allow_street_address(self, allow_street_address):
        """Sets the allow_street_address of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow street addresses in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_street_address: The allow_street_address of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_street_address = allow_street_address

    @property
    def allow_city(self):
        """Gets the allow_city of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow standalone city names (e.g. \"San Francisco\") in the audio transcript and not flag them as PII. Applies to city names mentioned outside of a full street address.  # noqa: E501

        :return: The allow_city of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_city

    @allow_city.setter
    def allow_city(self, allow_city):
        """Sets the allow_city of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow standalone city names (e.g. \"San Francisco\") in the audio transcript and not flag them as PII. Applies to city names mentioned outside of a full street address.  # noqa: E501

        :param allow_city: The allow_city of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_city = allow_city

    @property
    def allow_person_name(self):
        """Gets the allow_person_name of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow person names in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_person_name of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_person_name

    @allow_person_name.setter
    def allow_person_name(self, allow_person_name):
        """Sets the allow_person_name of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow person names in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_person_name: The allow_person_name of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_person_name = allow_person_name

    @property
    def allow_birth_date(self):
        """Gets the allow_birth_date of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow birth dates in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_birth_date of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_birth_date

    @allow_birth_date.setter
    def allow_birth_date(self, allow_birth_date):
        """Sets the allow_birth_date of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow birth dates in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_birth_date: The allow_birth_date of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_birth_date = allow_birth_date

    @property
    def allow_passport_number(self):
        """Gets the allow_passport_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow passport numbers in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_passport_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_passport_number

    @allow_passport_number.setter
    def allow_passport_number(self, allow_passport_number):
        """Sets the allow_passport_number of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow passport numbers in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_passport_number: The allow_passport_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_passport_number = allow_passport_number

    @property
    def allow_drivers_license(self):
        """Gets the allow_drivers_license of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow drivers license numbers in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_drivers_license of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_drivers_license

    @allow_drivers_license.setter
    def allow_drivers_license(self, allow_drivers_license):
        """Sets the allow_drivers_license of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow drivers license numbers in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_drivers_license: The allow_drivers_license of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_drivers_license = allow_drivers_license

    @property
    def allow_social_security_number(self):
        """Gets the allow_social_security_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow social security numbers in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_social_security_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_social_security_number

    @allow_social_security_number.setter
    def allow_social_security_number(self, allow_social_security_number):
        """Sets the allow_social_security_number of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow social security numbers in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_social_security_number: The allow_social_security_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_social_security_number = allow_social_security_number

    @property
    def allow_taxpayer_id(self):
        """Gets the allow_taxpayer_id of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow taxpayer IDs in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_taxpayer_id of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_taxpayer_id

    @allow_taxpayer_id.setter
    def allow_taxpayer_id(self, allow_taxpayer_id):
        """Sets the allow_taxpayer_id of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow taxpayer IDs in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_taxpayer_id: The allow_taxpayer_id of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_taxpayer_id = allow_taxpayer_id

    @property
    def allow_credit_card_number(self):
        """Gets the allow_credit_card_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow credit card numbers in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_credit_card_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_credit_card_number

    @allow_credit_card_number.setter
    def allow_credit_card_number(self, allow_credit_card_number):
        """Sets the allow_credit_card_number of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow credit card numbers in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_credit_card_number: The allow_credit_card_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_credit_card_number = allow_credit_card_number

    @property
    def allow_credit_card_expiration_date(self):
        """Gets the allow_credit_card_expiration_date of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow credit card expiration dates in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_credit_card_expiration_date of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_credit_card_expiration_date

    @allow_credit_card_expiration_date.setter
    def allow_credit_card_expiration_date(self, allow_credit_card_expiration_date):
        """Sets the allow_credit_card_expiration_date of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow credit card expiration dates in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_credit_card_expiration_date: The allow_credit_card_expiration_date of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_credit_card_expiration_date = allow_credit_card_expiration_date

    @property
    def allow_credit_card_verification_code(self):
        """Gets the allow_credit_card_verification_code of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow credit card verification codes in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_credit_card_verification_code of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_credit_card_verification_code

    @allow_credit_card_verification_code.setter
    def allow_credit_card_verification_code(self, allow_credit_card_verification_code):
        """Sets the allow_credit_card_verification_code of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow credit card verification codes in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_credit_card_verification_code: The allow_credit_card_verification_code of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_credit_card_verification_code = allow_credit_card_verification_code

    @property
    def allow_bank_account_number(self):
        """Gets the allow_bank_account_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow bank account numbers in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_bank_account_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_bank_account_number

    @allow_bank_account_number.setter
    def allow_bank_account_number(self, allow_bank_account_number):
        """Sets the allow_bank_account_number of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow bank account numbers in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_bank_account_number: The allow_bank_account_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_bank_account_number = allow_bank_account_number

    @property
    def allow_iban(self):
        """Gets the allow_iban of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow IBANs in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_iban of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_iban

    @allow_iban.setter
    def allow_iban(self, allow_iban):
        """Sets the allow_iban of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow IBANs in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_iban: The allow_iban of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_iban = allow_iban

    @property
    def allow_health_insurance_number(self):
        """Gets the allow_health_insurance_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow health insurance numbers in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_health_insurance_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_health_insurance_number

    @allow_health_insurance_number.setter
    def allow_health_insurance_number(self, allow_health_insurance_number):
        """Sets the allow_health_insurance_number of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow health insurance numbers in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_health_insurance_number: The allow_health_insurance_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_health_insurance_number = allow_health_insurance_number

    @property
    def allow_bearer_token(self):
        """Gets the allow_bearer_token of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow bearer tokens in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_bearer_token of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_bearer_token

    @allow_bearer_token.setter
    def allow_bearer_token(self, allow_bearer_token):
        """Sets the allow_bearer_token of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow bearer tokens in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_bearer_token: The allow_bearer_token of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_bearer_token = allow_bearer_token

    @property
    def allow_http_cookie(self):
        """Gets the allow_http_cookie of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow HTTP cookies in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_http_cookie of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_http_cookie

    @allow_http_cookie.setter
    def allow_http_cookie(self, allow_http_cookie):
        """Sets the allow_http_cookie of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow HTTP cookies in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_http_cookie: The allow_http_cookie of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_http_cookie = allow_http_cookie

    @property
    def allow_private_keys(self):
        """Gets the allow_private_keys of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow private keys in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_private_keys of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_private_keys

    @allow_private_keys.setter
    def allow_private_keys(self, allow_private_keys):
        """Sets the allow_private_keys of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow private keys in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_private_keys: The allow_private_keys of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_private_keys = allow_private_keys

    @property
    def allow_credentials(self):
        """Gets the allow_credentials of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow credentials (usernames/passwords) in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_credentials of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_credentials

    @allow_credentials.setter
    def allow_credentials(self, allow_credentials):
        """Sets the allow_credentials of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow credentials (usernames/passwords) in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_credentials: The allow_credentials of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_credentials = allow_credentials

    @property
    def allow_deep_web_urls(self):
        """Gets the allow_deep_web_urls of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow deep web URLs (.onion) in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_deep_web_urls of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_deep_web_urls

    @allow_deep_web_urls.setter
    def allow_deep_web_urls(self, allow_deep_web_urls):
        """Sets the allow_deep_web_urls of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow deep web URLs (.onion) in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_deep_web_urls: The allow_deep_web_urls of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_deep_web_urls = allow_deep_web_urls

    @property
    def allow_source_code(self):
        """Gets the allow_source_code of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow source code in the audio transcript and not flag it as sensitive data.  # noqa: E501

        :return: The allow_source_code of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_source_code

    @allow_source_code.setter
    def allow_source_code(self, allow_source_code):
        """Sets the allow_source_code of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow source code in the audio transcript and not flag it as sensitive data.  # noqa: E501

        :param allow_source_code: The allow_source_code of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_source_code = allow_source_code

    @property
    def allow_ip_address(self):
        """Gets the allow_ip_address of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow IP addresses in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_ip_address of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_ip_address

    @allow_ip_address.setter
    def allow_ip_address(self, allow_ip_address):
        """Sets the allow_ip_address of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow IP addresses in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_ip_address: The allow_ip_address of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_ip_address = allow_ip_address

    @property
    def allow_mac_address(self):
        """Gets the allow_mac_address of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow MAC addresses in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_mac_address of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_mac_address

    @allow_mac_address.setter
    def allow_mac_address(self, allow_mac_address):
        """Sets the allow_mac_address of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow MAC addresses in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_mac_address: The allow_mac_address of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_mac_address = allow_mac_address

    @property
    def allow_health_insurance_member_id(self):
        """Gets the allow_health_insurance_member_id of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow health insurance member IDs in the audio transcript and not flag them as PHI.  # noqa: E501

        :return: The allow_health_insurance_member_id of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_health_insurance_member_id

    @allow_health_insurance_member_id.setter
    def allow_health_insurance_member_id(self, allow_health_insurance_member_id):
        """Sets the allow_health_insurance_member_id of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow health insurance member IDs in the audio transcript and not flag them as PHI.  # noqa: E501

        :param allow_health_insurance_member_id: The allow_health_insurance_member_id of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_health_insurance_member_id = allow_health_insurance_member_id

    @property
    def allow_medical_record_number(self):
        """Gets the allow_medical_record_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow medical record numbers in the audio transcript and not flag them as PHI.  # noqa: E501

        :return: The allow_medical_record_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_medical_record_number

    @allow_medical_record_number.setter
    def allow_medical_record_number(self, allow_medical_record_number):
        """Sets the allow_medical_record_number of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow medical record numbers in the audio transcript and not flag them as PHI.  # noqa: E501

        :param allow_medical_record_number: The allow_medical_record_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_medical_record_number = allow_medical_record_number

    @property
    def allow_billing_account_number(self):
        """Gets the allow_billing_account_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow billing account numbers (e.g. provider/customer billing account IDs, distinct from bank account numbers) in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_billing_account_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_billing_account_number

    @allow_billing_account_number.setter
    def allow_billing_account_number(self, allow_billing_account_number):
        """Sets the allow_billing_account_number of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow billing account numbers (e.g. provider/customer billing account IDs, distinct from bank account numbers) in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_billing_account_number: The allow_billing_account_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_billing_account_number = allow_billing_account_number

    @property
    def allow_health_injury_or_disease(self):
        """Gets the allow_health_injury_or_disease of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow references to injuries or diseases in the audio transcript and not flag them as PHI.  # noqa: E501

        :return: The allow_health_injury_or_disease of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_health_injury_or_disease

    @allow_health_injury_or_disease.setter
    def allow_health_injury_or_disease(self, allow_health_injury_or_disease):
        """Sets the allow_health_injury_or_disease of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow references to injuries or diseases in the audio transcript and not flag them as PHI.  # noqa: E501

        :param allow_health_injury_or_disease: The allow_health_injury_or_disease of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_health_injury_or_disease = allow_health_injury_or_disease

    @property
    def allow_health_type_of_treatment(self):
        """Gets the allow_health_type_of_treatment of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow references to types of medical treatment in the audio transcript and not flag them as PHI.  # noqa: E501

        :return: The allow_health_type_of_treatment of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_health_type_of_treatment

    @allow_health_type_of_treatment.setter
    def allow_health_type_of_treatment(self, allow_health_type_of_treatment):
        """Sets the allow_health_type_of_treatment of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow references to types of medical treatment in the audio transcript and not flag them as PHI.  # noqa: E501

        :param allow_health_type_of_treatment: The allow_health_type_of_treatment of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_health_type_of_treatment = allow_health_type_of_treatment

    @property
    def allow_health_date_and_time_of_treatment(self):
        """Gets the allow_health_date_and_time_of_treatment of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow dates and times of medical treatment in the audio transcript and not flag them as PHI.  # noqa: E501

        :return: The allow_health_date_and_time_of_treatment of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_health_date_and_time_of_treatment

    @allow_health_date_and_time_of_treatment.setter
    def allow_health_date_and_time_of_treatment(self, allow_health_date_and_time_of_treatment):
        """Sets the allow_health_date_and_time_of_treatment of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow dates and times of medical treatment in the audio transcript and not flag them as PHI.  # noqa: E501

        :param allow_health_date_and_time_of_treatment: The allow_health_date_and_time_of_treatment of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_health_date_and_time_of_treatment = allow_health_date_and_time_of_treatment

    @property
    def allow_health_plan_beneficiary_number(self):
        """Gets the allow_health_plan_beneficiary_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow health plan beneficiary numbers in the audio transcript and not flag them as PHI.  # noqa: E501

        :return: The allow_health_plan_beneficiary_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_health_plan_beneficiary_number

    @allow_health_plan_beneficiary_number.setter
    def allow_health_plan_beneficiary_number(self, allow_health_plan_beneficiary_number):
        """Sets the allow_health_plan_beneficiary_number of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow health plan beneficiary numbers in the audio transcript and not flag them as PHI.  # noqa: E501

        :param allow_health_plan_beneficiary_number: The allow_health_plan_beneficiary_number of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_health_plan_beneficiary_number = allow_health_plan_beneficiary_number

    @property
    def allow_health_payments_made_for_treatment(self):
        """Gets the allow_health_payments_made_for_treatment of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow payments made for medical treatment in the audio transcript and not flag them as PHI.  # noqa: E501

        :return: The allow_health_payments_made_for_treatment of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_health_payments_made_for_treatment

    @allow_health_payments_made_for_treatment.setter
    def allow_health_payments_made_for_treatment(self, allow_health_payments_made_for_treatment):
        """Sets the allow_health_payments_made_for_treatment of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow payments made for medical treatment in the audio transcript and not flag them as PHI.  # noqa: E501

        :param allow_health_payments_made_for_treatment: The allow_health_payments_made_for_treatment of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_health_payments_made_for_treatment = allow_health_payments_made_for_treatment

    @property
    def allow_vehicle_id(self):
        """Gets the allow_vehicle_id of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow vehicle identifiers (e.g. license plates, VINs) in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_vehicle_id of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_vehicle_id

    @allow_vehicle_id.setter
    def allow_vehicle_id(self, allow_vehicle_id):
        """Sets the allow_vehicle_id of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow vehicle identifiers (e.g. license plates, VINs) in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_vehicle_id: The allow_vehicle_id of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_vehicle_id = allow_vehicle_id

    @property
    def allow_device_id(self):
        """Gets the allow_device_id of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs) in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_device_id of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_device_id

    @allow_device_id.setter
    def allow_device_id(self, allow_device_id):
        """Sets the allow_device_id of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs) in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_device_id: The allow_device_id of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_device_id = allow_device_id

    @property
    def allow_names_of_relatives(self):
        """Gets the allow_names_of_relatives of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow names of relatives in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_names_of_relatives of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_names_of_relatives

    @allow_names_of_relatives.setter
    def allow_names_of_relatives(self, allow_names_of_relatives):
        """Sets the allow_names_of_relatives of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow names of relatives in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_names_of_relatives: The allow_names_of_relatives of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_names_of_relatives = allow_names_of_relatives

    @property
    def allow_health_universal_record_locator(self):
        """Gets the allow_health_universal_record_locator of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow health universal record locators (URLs) in the audio transcript and not flag them as PHI.  # noqa: E501

        :return: The allow_health_universal_record_locator of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_health_universal_record_locator

    @allow_health_universal_record_locator.setter
    def allow_health_universal_record_locator(self, allow_health_universal_record_locator):
        """Sets the allow_health_universal_record_locator of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow health universal record locators (URLs) in the audio transcript and not flag them as PHI.  # noqa: E501

        :param allow_health_universal_record_locator: The allow_health_universal_record_locator of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_health_universal_record_locator = allow_health_universal_record_locator

    @property
    def allow_biometrics(self):
        """Gets the allow_biometrics of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to allow biometric data references (e.g. fingerprints, retinal scans, voiceprints) in the audio transcript and not flag them as PII.  # noqa: E501

        :return: The allow_biometrics of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_biometrics

    @allow_biometrics.setter
    def allow_biometrics(self, allow_biometrics):
        """Sets the allow_biometrics of this DlpAdvancedAudioDetectionRequest.

        Set to true to allow biometric data references (e.g. fingerprints, retinal scans, voiceprints) in the audio transcript and not flag them as PII.  # noqa: E501

        :param allow_biometrics: The allow_biometrics of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._allow_biometrics = allow_biometrics

    @property
    def provide_analysis_rationale(self):
        """Gets the provide_analysis_rationale of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Set to true to include a natural language rationale explaining why each detection conclusion was formed.  # noqa: E501

        :return: The provide_analysis_rationale of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._provide_analysis_rationale

    @provide_analysis_rationale.setter
    def provide_analysis_rationale(self, provide_analysis_rationale):
        """Sets the provide_analysis_rationale of this DlpAdvancedAudioDetectionRequest.

        Set to true to include a natural language rationale explaining why each detection conclusion was formed.  # noqa: E501

        :param provide_analysis_rationale: The provide_analysis_rationale of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: bool
        """

        self._provide_analysis_rationale = provide_analysis_rationale

    @property
    def custom_policy_id(self):
        """Gets the custom_policy_id of this DlpAdvancedAudioDetectionRequest.  # noqa: E501

        Apply a Custom Policy for DLP Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud  # noqa: E501

        :return: The custom_policy_id of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :rtype: str
        """
        return self._custom_policy_id

    @custom_policy_id.setter
    def custom_policy_id(self, custom_policy_id):
        """Sets the custom_policy_id of this DlpAdvancedAudioDetectionRequest.

        Apply a Custom Policy for DLP Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud  # noqa: E501

        :param custom_policy_id: The custom_policy_id of this DlpAdvancedAudioDetectionRequest.  # noqa: E501
        :type: str
        """

        self._custom_policy_id = custom_policy_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DlpAdvancedAudioDetectionRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DlpAdvancedAudioDetectionRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
