# coding: utf-8

"""
    dlpapi

    Easily and directly scan and detect sensitive data (PII) in input text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RedactedAudioSegment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start_time_ms': 'int',
        'end_time_ms': 'int',
        'redacted_text': 'str'
    }

    attribute_map = {
        'start_time_ms': 'StartTimeMs',
        'end_time_ms': 'EndTimeMs',
        'redacted_text': 'RedactedText'
    }

    def __init__(self, start_time_ms=None, end_time_ms=None, redacted_text=None):  # noqa: E501
        """RedactedAudioSegment - a model defined in Swagger"""  # noqa: E501

        self._start_time_ms = None
        self._end_time_ms = None
        self._redacted_text = None
        self.discriminator = None

        if start_time_ms is not None:
            self.start_time_ms = start_time_ms
        if end_time_ms is not None:
            self.end_time_ms = end_time_ms
        if redacted_text is not None:
            self.redacted_text = redacted_text

    @property
    def start_time_ms(self):
        """Gets the start_time_ms of this RedactedAudioSegment.  # noqa: E501

        Start time of the redacted segment in the audio, in milliseconds.  # noqa: E501

        :return: The start_time_ms of this RedactedAudioSegment.  # noqa: E501
        :rtype: int
        """
        return self._start_time_ms

    @start_time_ms.setter
    def start_time_ms(self, start_time_ms):
        """Sets the start_time_ms of this RedactedAudioSegment.

        Start time of the redacted segment in the audio, in milliseconds.  # noqa: E501

        :param start_time_ms: The start_time_ms of this RedactedAudioSegment.  # noqa: E501
        :type: int
        """

        self._start_time_ms = start_time_ms

    @property
    def end_time_ms(self):
        """Gets the end_time_ms of this RedactedAudioSegment.  # noqa: E501

        End time of the redacted segment in the audio, in milliseconds.  # noqa: E501

        :return: The end_time_ms of this RedactedAudioSegment.  # noqa: E501
        :rtype: int
        """
        return self._end_time_ms

    @end_time_ms.setter
    def end_time_ms(self, end_time_ms):
        """Sets the end_time_ms of this RedactedAudioSegment.

        End time of the redacted segment in the audio, in milliseconds.  # noqa: E501

        :param end_time_ms: The end_time_ms of this RedactedAudioSegment.  # noqa: E501
        :type: int
        """

        self._end_time_ms = end_time_ms

    @property
    def redacted_text(self):
        """Gets the redacted_text of this RedactedAudioSegment.  # noqa: E501

        The original text that was redacted in this segment.  # noqa: E501

        :return: The redacted_text of this RedactedAudioSegment.  # noqa: E501
        :rtype: str
        """
        return self._redacted_text

    @redacted_text.setter
    def redacted_text(self, redacted_text):
        """Sets the redacted_text of this RedactedAudioSegment.

        The original text that was redacted in this segment.  # noqa: E501

        :param redacted_text: The redacted_text of this RedactedAudioSegment.  # noqa: E501
        :type: str
        """

        self._redacted_text = redacted_text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RedactedAudioSegment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RedactedAudioSegment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
