Remove-Item –path ./cloudmersive_dlp_api_client –recurse

Invoke-WebRequest -Uri 'https://api.cloudmersive.com/dlp/v1/swagger.json' -OutFile '.\dlp-api-swagger.json'
(Get-Content .\dlp-api-swagger.json).replace('localhost', "api.cloudmersive.com") | Set-Content .\dlp-api-swagger.json
(Get-Content .\dlp-api-swagger.json).replace('"http"', '"https"') | Set-Content .\dlp-api-swagger.json

& java -jar swagger-codegen-cli-2.4.14.jar generate -i .\dlp-api-swagger.json -l python -c packageconfig.json
#(Get-Content ./client/package.json).replace('v1', '1.0.1') | Set-Content ./client/package.json

# Bug fix

$newcontent = (Get-Content ./core/replace.py -Raw)
Write-Host $newcontent
(Get-Content ./cloudmersive_dlp_api_client/api_client.py).replace('if response_type:', $newcontent) | Set-Content ./cloudmersive_dlp_api_client/api_client.py
(Get-Content ./cloudmersive_dlp_api_client/rest.py).replace((Get-Content ./core/rest_match.py -Raw), (Get-Content ./core/rest_replace.py -Raw)) | Set-Content ./cloudmersive_dlp_api_client/rest.py

$extrasetup = (Get-Content ./extrasetup.py) -join "`n"
Write-Host $extrasetup
(Get-Content ./setup.py).replace('# http://pypi.python.org/pypi/setuptools', $extrasetup) | Set-Content ./setup.py
(Get-Content ./setup.py).replace('"""\', "long_description,`n    long_description_content_type='text/markdown'") | Set-Content ./setup.py


(Get-Content ./setup.py).replace('Easily and directly scan and detect sensitive data (PII) in input text.  # noqa: E501', '') | Set-Content ./setup.py

(Get-Content ./setup.py).replace('    """', '') | Set-Content ./setup.py
(Get-Content ./README.md).replace('This Python package is automatically generated by the [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) project:', 'This Python package provides a native API client for [Cloudmersive DLP API](https://cloudmersive.com/dlp-data-loss-prevention-api)') | Set-Content ./README.md
Write-Host "Done."